# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(212121)
$foreground = rgb(E3E3E3)
$color0 = rgb(474747)
$color1 = rgb(191919)
$color2 = rgb(1F1F1F)
$color3 = rgb(4A4A4A)
$color4 = rgb(4E4E4E)
$color5 = rgb(777777)
$color6 = rgb(848484)
$color7 = rgb(CFCFCF)
$color8 = rgb(919191)
$color9 = rgb(212121)
$color10 = rgb(2A2A2A)
$color11 = rgb(636363)
$color12 = rgb(686969)
$color13 = rgb(9E9E9E)
$color14 = rgb(B0B0B0)
$color15 = rgb(CFCFCF)
