-- Auto-generated by ii wallpaper theming system
-- Do not edit manually - changes will be overwritten

return {
  foreground = '#ADAAA2',
  background = '#151617',

  cursor_bg = '#ADAAA2',
  cursor_fg = '#151617',
  cursor_border = '#ADAAA2',

  selection_fg = '#151617',
  selection_bg = '#ADAAA2',

  scrollbar_thumb = '#747676',
  split = '#747676',

  ansi = {
    '#151617',  -- black
    '#B78DDB',  -- red
    '#88C5B0',  -- green
    '#AEBC86',  -- yellow
    '#7AACC7',  -- blue
    '#9FA4CC',  -- magenta
    '#85CED2',  -- cyan
    '#ADAAA2',  -- white
  },

  brights = {
    '#747676',  -- bright black
    '#CDB1E3',  -- bright red
    '#A3DEC9', -- bright green
    '#C7D4AA', -- bright yellow
    '#9CCDE9', -- bright blue
    '#C1C6EE', -- bright magenta
    '#A6F0F3', -- bright cyan
    '#E5E5E6', -- bright white
  },

  tab_bar = {
    background = '#151617',
    active_tab = {
      bg_color = '#BFC8CB',
      fg_color = '#394244',
    },
    inactive_tab = {
      bg_color = '#747676',
      fg_color = '#ADAAA2',
    },
    inactive_tab_hover = {
      bg_color = '#747676',
      fg_color = '#E5E5E6',
    },
  },
}
