# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3E3E3
background         #212121
cursor             #878787

active_tab_foreground     #212121
active_tab_background     #E3E3E3
inactive_tab_foreground   #E3E3E3
inactive_tab_background   #212121

active_border_color   #E3E3E3
inactive_border_color #212121
bell_border_color     #191919

color0      #474747
color1		#191919
color2		#1F1F1F
color3		#4A4A4A
color4		#4E4E4E
color5		#777777
color6		#848484
color7		#CFCFCF
color8		#919191
color9		#212121
color10		#2A2A2A
color11		#636363
color12		#686969
color13		#9E9E9E
color14		#B0B0B0
color15		#CFCFCF
