[General]
x=0
y=0

[caching]
lastCacheFileHash=@ByteArray(f7afb40e587746128538d84f217bf478a23af59484d4db77f2d06bf647f7c82e)
lastDownloadSHA256=@ByteArray(19b108fe07cff2b5cd7df0f76b6d7325e43fb2a1d5418d10f6bd56642e0e8579)
lastFileName=/home/nahom/.cache/Raspberry Pi/Imager/lastdownload.cache

[imagecustomization]
hostname=nahom
sshEnabled=true
sshUserName=nahom
sshUserPassword=$5$Na5x4XthHB$c5Rkuf2vZ4qjsLKUpiyT9kuGUVOcY2WLmMFxvgAIDeA
wifiCountry=GB
wifiPassword=Peanut1972
wifiSSID=Hiwote_EXT
wifiSSIDHidden=false
